/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqliteTerminalJava;

import com.almworks.sqlite4java.SQLiteConnection; 

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
