/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqliteTerminalJava;

import com.almworks.sqlite4java.SQLiteConnection; 

public class App {

    public static void main(String[] args) {
        SQLShellApp sqlShellApp = new SQLShellApp();
        sqlShellApp.run();
    }
}
